### ISSUE TITLE
Notifications silent while pushing

### ISSUE THREAD

**Issue by pstryk** [Azelphur/pyPushBullet#49] opened 2017-12-08 12:29 UTC
Hi,
I am pushing notes from python script and I noticed that those notifications are silent on my device (no notification that I have new note). This those not happen when I push from other devices.

Could this be related to api itself?

**Comment by Azelphur** [comment] 2017-12-15 16:51
Honestly not sure, I don't know of anything in the API that would cause this behaviour.

**Comment by Nadim96** [comment] 2018-01-07 23:58
same issue, did you fix it?
  

EDIT fixed: changed devices[0] to devices[1], it wasn't sending it to my phone but to my pc with [0] since that's the first device in my case. [1] is currently my phone

**Comment by Azelphur** [comment] 2018-01-08 13:43
I've had a read over the API documentation again for creating a push ( https://docs.pushbullet.com/#create-push ) and I can see no mention of anything that'd control whether a notification is silent or not on the phones side.

This means the issue is entirely out of my control, you'd need to contact the PushBullet app developers for support with this issue.

Sorry I can't be of more assistance, I'm going to close this now, but feel free to reopen it if you have something more to add.

**Closed as completed by Azelphur** 2018-01-08 13:43 UTC
